name: nur_kitab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  audioplayers: ^6.6.0
  geolocator: ^13.0.0 
  geocoding: ^3.0.0
  shared_preferences: ^2.3.0
  flutter_local_notifications: ^22.0.1
  timezone: ^0.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - asset/images/
    - asset/json/
    - asset/json/surah/

  fonts:
    - family: Amiri
      fonts:
        - asset: asset/fonts/AmiriQuran.ttf
    - family: ArefRuqaa
      fonts:
        - asset: asset/fonts/ArefRuqaa.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  min_sdk_android: 21