const List<Map<String, dynamic>> juzMapping = [
  {'juz': 1, 'start_sura': 1, 'start_aya': 1, 'end_sura': 2, 'end_aya': 141},
  {'juz': 2, 'start_sura': 2, 'start_aya': 142, 'end_sura': 2, 'end_aya': 252},
  {'juz': 3, 'start_sura': 2, 'start_aya': 253, 'end_sura': 3, 'end_aya': 91},
  {'juz': 4, 'start_sura': 3, 'start_aya': 92, 'end_sura': 4, 'end_aya': 23},
  {'juz': 5, 'start_sura': 4, 'start_aya': 24, 'end_sura': 4, 'end_aya': 147},
  {'juz': 6, 'start_sura': 4, 'start_aya': 148, 'end_sura': 5, 'end_aya': 82},
  {'juz': 7, 'start_sura': 5, 'start_aya': 83, 'end_sura': 6, 'end_aya': 110},
  {'juz': 8, 'start_sura': 6, 'start_aya': 111, 'end_sura': 7, 'end_aya': 87},
  {'juz': 9, 'start_sura': 7, 'start_aya': 88, 'end_sura': 8, 'end_aya': 40},
  {'juz': 10, 'start_sura': 8, 'start_aya': 41, 'end_sura': 9, 'end_aya': 93},
  {'juz': 11, 'start_sura': 9, 'start_aya': 94, 'end_sura': 11, 'end_aya': 5},
  {'juz': 12, 'start_sura': 11, 'start_aya': 6, 'end_sura': 12, 'end_aya': 52},
  {'juz': 13, 'start_sura': 12, 'start_aya': 53, 'end_sura': 15, 'end_aya': 1},
  {'juz': 14, 'start_sura': 15, 'start_aya': 2, 'end_sura': 16, 'end_aya': 128},
  {'juz': 15, 'start_sura': 17, 'start_aya': 1, 'end_sura': 18, 'end_aya': 74},
  {'juz': 16, 'start_sura': 18, 'start_aya': 75, 'end_sura': 20, 'end_aya': 135},
  {'juz': 17, 'start_sura': 21, 'start_aya': 1, 'end_sura': 22, 'end_aya': 78},
  {'juz': 18, 'start_sura': 23, 'start_aya': 1, 'end_sura': 25, 'end_aya': 20},
  {'juz': 19, 'start_sura': 25, 'start_aya': 21, 'end_sura': 27, 'end_aya': 59},
  {'juz': 20, 'start_sura': 27, 'start_aya': 60, 'end_sura': 29, 'end_aya': 44},
  {'juz': 21, 'start_sura': 29, 'start_aya': 45, 'end_sura': 33, 'end_aya': 30},
  {'juz': 22, 'start_sura': 33, 'start_aya': 31, 'end_sura': 36, 'end_aya': 21},
  {'juz': 23, 'start_sura': 36, 'start_aya': 22, 'end_sura': 39, 'end_aya': 31},
  {'juz': 24, 'start_sura': 39, 'start_aya': 32, 'end_sura': 41, 'end_aya': 46},
  {'juz': 25, 'start_sura': 41, 'start_aya': 47, 'end_sura': 45, 'end_aya': 37},
  {'juz': 26, 'start_sura': 46, 'start_aya': 1, 'end_sura': 51, 'end_aya': 30},
  {'juz': 27, 'start_sura': 51, 'start_aya': 31, 'end_sura': 57, 'end_aya': 29},
  {'juz': 28, 'start_sura': 58, 'start_aya': 1, 'end_sura': 66, 'end_aya': 12},
  {'juz': 29, 'start_sura': 67, 'start_aya': 1, 'end_sura': 77, 'end_aya': 50},
  {'juz': 30, 'start_sura': 78, 'start_aya': 1, 'end_sura': 114, 'end_aya': 6},
];

const List<String> arabicJuzNames = [
  "الجزء الأول",
  "الجزء الثاني",
  "الجزء الثالث",
  "الجزء الرابع",
  "الجزء الخامس",
  "الجزء السادس",
  "الجزء السابع",
  "الجزء الثامن",
  "الجزء التاسع",
  "الجزء العاشر",
  "الجزء الحادي عشر",
  "الجزء الثاني عشر",
  "الجزء الثالث عشر",
  "الجزء الرابع عشر",
  "الجزء الخامس عشر",
  "الجزء السادس عشر",
  "الجزء السابع عشر",
  "الجزء الثامن عشر",
  "الجزء التاسع عشر",
  "الجزء العشرون",
  "الجزء الحادي والعشرون",
  "الجزء الثاني والعشرون",
  "الجزء الثالث والعشرون",
  "الجزء الرابع والعشرون",
  "الجزء الخامس والعشرون",
  "الجزء السادس والعشرون",
  "الجزء السابع والعشرون",
  "الجزء الثامن والعشرون",
  "الجزء التاسع والعشرون",
  "الجزء الثلاثون",
];
